@startuml
  "express" -> "on-finished"
  "express" -> "body-parser"
  "express" -> "statuses"
  "express" -> "cookie-signature"
  "express" -> "content-type"
  "express" -> "range-parser"
  "express" -> "setprototypeof"
  "express" -> "qs"
  "express" -> "utils-merge"
  "express" -> "send"
  "express" -> "proxy-addr"
  "express" -> "accepts"
  "express" -> "safe-buffer"
  "express" -> "parseurl"
  "express" -> "merge-descriptors"
  "express" -> "cookie"
  "express" -> "http-errors"
  "express" -> "serve-static"
  "express" -> "type-is"
  "express" -> "encodeurl"
  "express" -> "depd"
  "express" -> "etag"
  "express" -> "vary"
  "express" -> "debug"
  "express" -> "path-to-regexp"
  "express" -> "array-flatten"
  "express" -> "methods"
  "express" -> "escape-html"
  "express" -> "fresh"
  "express" -> "finalhandler"
  "express" -> "content-disposition"
  "on-finished" -> "ee-first"
  "body-parser" -> "qs"
  "body-parser" -> "content-type"
  "body-parser" -> "on-finished"
  "body-parser" -> "http-errors"
  "body-parser" -> "unpipe"
  "body-parser" -> "debug"
  "body-parser" -> "raw-body"
  "body-parser" -> "type-is"
  "body-parser" -> "depd"
  "body-parser" -> "iconv-lite"
  "body-parser" -> "destroy"
  "body-parser" -> "bytes"
  "qs" -> "side-channel"
  "side-channel" -> "side-channel-list"
  "side-channel" -> "es-errors"
  "side-channel" -> "side-channel-map"
  "side-channel" -> "side-channel-weakmap"
  "side-channel" -> "object-inspect"
  "side-channel-list" -> "es-errors"
  "side-channel-list" -> "object-inspect"
  "side-channel-map" -> "es-errors"
  "side-channel-map" -> "call-bound"
  "side-channel-map" -> "object-inspect"
  "side-channel-map" -> "get-intrinsic"
  "call-bound" -> "call-bind-apply-helpers"
  "call-bound" -> "get-intrinsic"
  "call-bind-apply-helpers" -> "function-bind"
  "call-bind-apply-helpers" -> "es-errors"
  "get-intrinsic" -> "function-bind"
  "get-intrinsic" -> "es-object-atoms"
  "get-intrinsic" -> "gopd"
  "get-intrinsic" -> "es-define-property"
  "get-intrinsic" -> "dunder-proto"
  "get-intrinsic" -> "hasown"
  "get-intrinsic" -> "call-bind-apply-helpers"
  "get-intrinsic" -> "es-errors"
  "get-intrinsic" -> "has-symbols"
  "get-intrinsic" -> "math-intrinsics"
  "es-object-atoms" -> "es-errors"
  "dunder-proto" -> "gopd"
  "dunder-proto" -> "call-bind-apply-helpers"
  "dunder-proto" -> "es-errors"
  "hasown" -> "function-bind"
  "side-channel-weakmap" -> "get-intrinsic"
  "side-channel-weakmap" -> "call-bound"
  "side-channel-weakmap" -> "es-errors"
  "side-channel-weakmap" -> "side-channel-map"
  "side-channel-weakmap" -> "object-inspect"
  "http-errors" -> "inherits"
  "http-errors" -> "depd"
  "http-errors" -> "toidentifier"
  "http-errors" -> "statuses"
  "http-errors" -> "setprototypeof"
  "debug" -> "ms"
  "raw-body" -> "http-errors"
  "raw-body" -> "unpipe"
  "raw-body" -> "bytes"
  "raw-body" -> "iconv-lite"
  "iconv-lite" -> "safer-buffer"
  "type-is" -> "media-typer"
  "type-is" -> "mime-types"
  "mime-types" -> "mime-db"
  "send" -> "on-finished"
  "send" -> "http-errors"
  "send" -> "debug"
  "send" -> "encodeurl"
  "send" -> "depd"
  "send" -> "mime"
  "send" -> "ms"
  "send" -> "statuses"
  "send" -> "escape-html"
  "send" -> "etag"
  "send" -> "fresh"
  "send" -> "destroy"
  "send" -> "range-parser"
  "proxy-addr" -> "ipaddr.js"
  "proxy-addr" -> "forwarded"
  "accepts" -> "negotiator"
  "accepts" -> "mime-types"
  "serve-static" -> "escape-html"
  "serve-static" -> "send"
  "serve-static" -> "encodeurl"
  "serve-static" -> "parseurl"
  "finalhandler" -> "on-finished"
  "finalhandler" -> "unpipe"
  "finalhandler" -> "debug"
  "finalhandler" -> "parseurl"
  "finalhandler" -> "encodeurl"
  "finalhandler" -> "statuses"
  "finalhandler" -> "escape-html"
  "content-disposition" -> "safe-buffer"
@enduml